version: "3.1"

services:
  strapi:
    env_file: .env
    command: yarn develop
    working_dir: /workspace
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ./:/workspace
      - nodemodules:/workspace/node_modules
    ports:
      - 1337:1337
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:14-alpine
    env_file: .env
    volumes:
      - pgdatav4:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    hostname: pgadmin4
    image: dpage/pgadmin4
    ports:
      - 6004:80
    environment:
      PGADMIN_DEFAULT_EMAIL: "dev@zrp.com.br"
      PGADMIN_DEFAULT_PASSWORD: "zrp@1234"
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  pgdatav4:
  nodemodules:
